In [1]:
import tensorflow as tf

In [2]:
import tensorflow_hub as hub

In [4]:
import pandas as pd

In [7]:
import torch

In [9]:
tokenizer = torch.hub.load('huggingface/pytorch-transformers', 'tokenizer', 'bert-base-uncased') 

Using cache found in /Users/rweng/.cache/torch/hub/huggingface_pytorch-transformers_master


In [11]:
model = torch.hub.load('huggingface/pytorch-transformers', 'model', 'bert-base-uncased')

Using cache found in /Users/rweng/.cache/torch/hub/huggingface_pytorch-transformers_master


In [12]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          

In [13]:
model_sc = torch.hub.load('huggingface/pytorch-transformers', 'modelForSequenceClassification', 'bert-base-uncased')

Using cache found in /Users/rweng/.cache/torch/hub/huggingface_pytorch-transformers_master


In [14]:
train_data = pd.read_csv('data/train.csv')
test_data = pd.read_csv('data/test.csv')

In [15]:
train_data.head()

qa_id                                     question_title  \
0      0  What am I losing when using extension tubes in...   
1      1  What is the distinction between a city and a s...   
2      2  Maximum protusion length for through-hole comp...   
3      3              Can an affidavit be used in Beit Din?   
4      5       How do you make a binary image in Photoshop?   

                                       question_body question_user_name  \
0  After playing around with macro photography on...               ysap   
1  I am trying to understand what kinds of places...      russellpierce   
2  I'm working on a PCB that has through-hole com...          Joe Baker   
3  An affidavit, from what i understand, is basic...         Scimonster   
4  I am trying to make a binary image. I want mor...            leigero   

                                  question_user_page  \
0         https://photo.stackexchange.com/users/1024   
1           https://rpg.stackexchange.com/users/8774   
2  https://electronics.stackexchange.com/users/10157   
3       https://judaism.stackexchange.com/users/5151   
4  https://graphicdesign.stackexchange.com/users/...   

                                              answer answer_user_name  \
0  I just got extension tubes, so here's the skin...           rfusca   
1  It might be helpful to look into the definitio...     Erik Schmidt   
2  Do you even need grooves?  We make several pro...      Dwayne Reid   
3  Sending an "affidavit" it is a dispute between...    Y     e     z   
4  Check out Image Trace in Adobe Illustrator. \n...             q2ra   

                                    answer_user_page  \
0         https://photo.stackexchange.com/users/1917   
1           https://rpg.stackexchange.com/users/1871   
2  https://electronics.stackexchange.com/users/64754   
3       https://judaism.stackexchange.com/users/4794   
4  https://graphicdesign.stackexchange.com/users/...   

                                                 url   category  ...  \
0  http://photo.stackexchange.com/questions/9169/...  LIFE_ARTS  ...   
1  http://rpg.stackexchange.com/questions/47820/w...    CULTURE  ...   
2  http://electronics.stackexchange.com/questions...    SCIENCE  ...   
3  http://judaism.stackexchange.com/questions/551...    CULTURE  ...   
4  http://graphicdesign.stackexchange.com/questio...  LIFE_ARTS  ...   

  question_well_written  answer_helpful  answer_level_of_information  \
0              1.000000        1.000000                     0.666667   
1              0.888889        0.888889                     0.555556   
2              0.777778        0.777778                     0.555556   
3              0.888889        0.833333                     0.333333   
4              1.000000        1.000000                     0.666667   

   answer_plausible  answer_relevance  answer_satisfaction  \
0          1.000000          1.000000             0.800000   
1          0.888889          0.888889             0.666667   
2          1.000000          1.000000             0.666667   
3          0.833333          1.000000             0.800000   
4          1.000000          1.000000             0.800000   

   answer_type_instructions  answer_type_procedure  \
0                       1.0               0.000000   
1                       0.0               0.000000   
2                       0.0               0.333333   
3                       0.0               0.000000   
4                       1.0               0.000000   

   answer_type_reason_explanation  answer_well_written  
0                        0.000000             1.000000  
1                        0.666667             0.888889  
2                        1.000000             0.888889  
3                        1.000000             1.000000  
4                        1.000000             1.000000  

[5 rows x 41 columns]

In [5]:
train_data.columns

Index(['qa_id', 'question_title', 'question_body', 'question_user_name',
       'question_user_page', 'answer', 'answer_user_name', 'answer_user_page',
       'url', 'category', 'host', 'question_asker_intent_understanding',
       'question_body_critical', 'question_conversational',
       'question_expect_short_answer', 'question_fact_seeking',
       'question_has_commonly_accepted_answer',
       'question_interestingness_others', 'question_interestingness_self',
       'question_multi_intent', 'question_not_really_a_question',
       'question_opinion_seeking', 'question_type_choice',
       'question_type_compare', 'question_type_consequence',
       'question_type_definition', 'question_type_entity',
       'question_type_instructions', 'question_type_procedure',
       'question_type_reason_explanation', 'question_type_spelling',
       'question_well_written', 'answer_helpful',
       'answer_level_of_information', 'answer_plausible', 'answer_relevance',
       'answer_satisfa

In [7]:
train_data.describe()

qa_id  question_asker_intent_understanding  \
count  6079.000000                          6079.000000   
mean   4829.665899                             0.892663   
std    2789.689555                             0.132047   
min       0.000000                             0.333333   
25%    2389.000000                             0.777778   
50%    4847.000000                             0.888889   
75%    7222.000000                             1.000000   
max    9647.000000                             1.000000   

       question_body_critical  question_conversational  \
count             6079.000000              6079.000000   
mean                 0.595301                 0.057301   
std                  0.219470                 0.182196   
min                  0.333333                 0.000000   
25%                  0.444444                 0.000000   
50%                  0.555556                 0.000000   
75%                  0.777778                 0.000000   
max                  1.000000                 1.000000   

       question_expect_short_answer  question_fact_seeking  \
count                   6079.000000            6079.000000   
mean                       0.698525               0.772633   
std                        0.350938               0.303023   
min                        0.000000               0.000000   
25%                        0.500000               0.666667   
50%                        0.666667               1.000000   
75%                        1.000000               1.000000   
max                        1.000000               1.000000   

       question_has_commonly_accepted_answer  question_interestingness_others  \
count                            6079.000000                      6079.000000   
mean                                0.793689                         0.587478   
std                                 0.336622                         0.135900   
min                                 0.000000                         0.333333   
25%                                 0.666667                         0.444444   
50%                                 1.000000                         0.555556   
75%                                 1.000000                         0.666667   
max                                 1.000000                         1.000000   

       question_interestingness_self  question_multi_intent  ...  \
count                    6079.000000            6079.000000  ...   
mean                        0.507275               0.238745  ...   
std                         0.185987               0.335057  ...   
min                         0.333333               0.000000  ...   
25%                         0.333333               0.000000  ...   
50%                         0.444444               0.000000  ...   
75%                         0.666667               0.333333  ...   
max                         1.000000               1.000000  ...   

       question_well_written  answer_helpful  answer_level_of_information  \
count            6079.000000     6079.000000                  6079.000000   
mean                0.799931        0.925408                     0.654823   
std                 0.178420        0.114836                     0.107666   
min                 0.333333        0.333333                     0.333333   
25%                 0.666667        0.888889                     0.666667   
50%                 0.833333        1.000000                     0.666667   
75%                 1.000000        1.000000                     0.666667   
max                 1.000000        1.000000                     1.000000   

       answer_plausible  answer_relevance  answer_satisfaction  \
count       6079.000000       6079.000000          6079.000000   
mean           0.960054          0.968626             0.854680   
std            0.086926          0.074631             0.130743   
min            0.333333          0.333333             0.200000   
25%            1.000000         

In [45]:
text_1 = "Who was Jimmy Henson ?"
text_2 = "Jim Henson was a puppeteer."

# Tokenized input with special tokens around it (for BERT: [CLS] at the beginning and [SEP] at the end)
indexed_tokens = tokenizer.encode(text_1, text_2, add_special_tokens=True)

In [46]:
tokenizer.tokenize(text_1)

['who', 'was', 'jimmy', 'henson', '?']

In [47]:
tokenizer.tokenize(text_2)

['jim', 'henson', 'was', 'a', 'puppet', '##eer', '.']

In [44]:
indexed_tokens

[101,
 2040,
 1059,
 3736,
 5261,
 27227,
 1029,
 102,
 3958,
 27227,
 2001,
 1037,
 13997,
 11510,
 1012,
 102]

In [40]:
tokenizer.ids_to_tokens[5261]

'jimmy'

In [49]:
segments_tensors = torch.tensor([segments_ids])

In [50]:
segments_tensors

tensor([[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]])

In [51]:
tokens_tensor = torch.tensor([indexed_tokens])

In [52]:
tokens_tensor

tensor([[  101,  2040,  2001,  5261, 27227,  1029,   102,  3958, 27227,  2001,
          1037, 13997, 11510,  1012,   102]])

In [53]:
# Define sentence A and B indices associated to 1st and 2nd sentences (see paper)
segments_ids = [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]

# Convert inputs to PyTorch tensors
segments_tensors = torch.tensor([segments_ids])
tokens_tensor = torch.tensor([indexed_tokens])

# model = torch.hub.load('huggingface/pytorch-transformers', 'model', 'bert-base-uncased')

with torch.no_grad():
    encoded_layers, _ = model(tokens_tensor, token_type_ids=segments_tensors)

In [54]:
encoded_layers

tensor([[[-0.4240,  0.2151, -0.8330,  ..., -1.0132,  0.7618,  0.6525],
         [-0.7718, -0.2736, -0.5494,  ..., -0.0212,  0.7109, -0.2639],
         [ 0.0835, -0.5506, -0.3897,  ..., -0.1108,  0.5886,  0.1662],
         ...,
         [-0.0454, -0.0224,  0.2818,  ...,  0.0837,  0.2598, -0.6440],
         [ 0.6700,  0.1874, -0.4618,  ...,  0.2196, -0.4222, -0.2313],
         [ 0.6586,  0.1840, -0.4281,  ...,  0.2181, -0.4304, -0.2145]]])

In [55]:
_

tensor([[-0.9933, -0.9174, -0.9997,  0.9896,  0.9854, -0.8039,  0.9979,  0.8225,
         -0.9983, -1.0000, -0.9680,  0.9995,  0.9943,  0.9654,  0.9947, -0.9853,
         -0.9559, -0.9154,  0.8017, -0.9606,  0.9685,  1.0000, -0.8347,  0.8349,
          0.9031,  1.0000, -0.9850,  0.9872,  0.9923,  0.9129, -0.9775,  0.8169,
         -0.9955, -0.7564, -0.9995, -0.9997,  0.9098, -0.9415, -0.7213, -0.7145,
         -0.9831,  0.8563,  1.0000,  0.5766,  0.8930, -0.8394, -1.0000,  0.7998,
         -0.9696,  0.9998,  0.9992,  0.9989,  0.8349,  0.9414,  0.9340, -0.9167,
          0.6670,  0.7630, -0.7886, -0.9586, -0.9098,  0.8769, -0.9982, -0.9909,
          0.9998,  0.9986, -0.8408, -0.8523, -0.8086,  0.7480,  0.9965,  0.7980,
         -0.8701, -0.9587,  0.9971,  0.8546, -0.8908,  1.0000, -0.9342, -0.9952,
          0.9980,  0.9985,  0.8919, -0.9880,  0.9890, -1.0000,  0.9610, -0.6543,
         -0.9963,  0.8276,  0.9536, -0.8386,  0.9918,  0.9046, -0.9765, -0.9190,
         -0.8987, -0.9978, -